[project]
name = "software_engineer_team"
version = "0.1.0"
description = "software_engineer_team using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[anthropic,tools]==1.14.4",
]

[project.scripts]
software_engineer_team = "software_engineer_team.main:run"
run_crew = "software_engineer_team.main:run"
train = "software_engineer_team.main:train"
replay = "software_engineer_team.main:replay"
test = "software_engineer_team.main:test"
run_with_trigger = "software_engineer_team.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
